apiVersion: v1
kind: Service
metadata:
    labels:
        app: python-helloworld
        app.kubernetes.io/instancei: python-helloworld
spec:
    type: NodePort
    selector:
        app: python-helloworld
    ports:
        - port: 80
          targetPort: 80
          nodePort: 30010
