apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
    tag: alpine
  name: nginx-alpine
  namespace: demo
spec:
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 8111
  selector:
    app: nginx
    tag: alpine
  type: ClusterIP
