apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-development
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values-prod.yaml
    path: helm/nginx-development
    repoURL: https://github.com/jpurusho/argocd 
    targetRevision: HEAD